In [5]:
import numpy as np

In [1]:
#генерация случайной матрицы

In [2]:
x = np.random.normal(loc=1, scale=10, size = (1000,50))

In [3]:
print (x)

[[ -9.77205212   7.5143015   -1.37073384 ..., -12.65842062   9.66668251
  -15.63241645]
 [-11.61224796  25.77111018  18.57162552 ...,  -9.58553057   5.87436542
   -8.14690714]
 [ 19.15653413   5.55122903  -6.66571427 ...,   3.70095142  -5.22800608
    7.50219566]
 ..., 
 [ 15.18741153   4.03325003  13.19174066 ...,  -5.84446541 -14.45786976
  -14.94321887]
 [ -3.568361     6.31764767  -4.08873219 ..., -20.41317769  -4.92525744
   -9.60983466]
 [ -6.38456523  -6.28600898  -5.83070699 ...,   4.98385345   8.33840042
    8.84636299]]


In [2]:
#нормировка: вычитание из каждого столбца его ср.значения, деление на его станд.отклонение

In [4]:
m = np.mean(x, axis=0)
std = np.std(x, axis=0)
x_norm = ((x-m)/std)


In [6]:
print (x_norm)

[[-1.12603789  0.65040115 -0.29167543 ..., -1.38630031  0.8250472
  -1.73534539]
 [-1.31808645  2.47504339  1.76386523 ..., -1.08355562  0.45014746
  -0.96195982]
 [ 1.89303931  0.45420559 -0.83745074 ...,  0.22544399 -0.64740744
   0.6548694 ]
 ..., 
 [ 1.47880933  0.30249405  1.20933846 ..., -0.71498154 -1.55985052
  -1.66413908]
 [-0.4786014   0.53080385 -0.57183065 ..., -2.15030797 -0.6174784
  -1.11310612]
 [-0.77250923 -0.72884479 -0.75138312 ...,  0.35183699  0.69373629
   0.79374567]]


In [3]:
#номера строк матрицы, сумма эл-тов которых больше 10

In [7]:
l = np.sum(x, axis=1)
print(np.nonzero(l>10))

(array([  0,   1,   2,   5,   6,   7,   8,  10,  12,  13,  16,  17,  20,
        22,  24,  25,  26,  27,  28,  29,  31,  32,  33,  34,  35,  37,
        38,  41,  42,  44,  45,  47,  48,  49,  50,  51,  52,  53,  54,
        55,  56,  58,  59,  61,  63,  65,  66,  68,  69,  70,  71,  72,
        73,  75,  76,  77,  80,  84,  85,  87,  88,  89,  93,  95,  96,
        97,  98,  99, 100, 108, 109, 111, 112, 113, 115, 116, 117, 118,
       119, 120, 121, 122, 123, 124, 125, 128, 129, 130, 131, 132, 133,
       135, 138, 139, 140, 141, 142, 145, 146, 148, 149, 152, 153, 154,
       155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 166, 169, 170,
       171, 174, 175, 177, 179, 180, 181, 184, 185, 186, 190, 192, 193,
       194, 195, 196, 197, 199, 200, 201, 203, 205, 206, 207, 208, 210,
       211, 214, 215, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228,
       229, 231, 232, 233, 235, 236, 238, 239, 240, 241, 242, 244, 245,
       246, 250, 251, 252, 253, 256, 257, 259, 260, 261, 262, 2

In [7]:
z = np.array([[4,5,0],
            [1,9,3],
            [5,1,1],
            [3,3,3],
            [9,9,9],
            [4,7,1]])

In [10]:
r = np.sum(z, axis=1)
print(np.nonzero(r>10))

(array([1, 4, 5], dtype=int32),)


In [ ]:
#генерация единичных матриц и склеивание

In [8]:
a = np.eye(3)
b = np.eye(3)

In [9]:
a

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [11]:
ab = np.vstack((a,b))

In [12]:
ab

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])